USE DATABASE PROPERTY_ANALYTICS;
USE SCHEMA RAW;



CREATE TABLE IF NOT EXISTS PROPERTY_ANALYTICS.RAW.LAND_REGISTRY_FILE_INGESTION_AUDIT (
    FILE_INGESTION_ID       NUMBER AUTOINCREMENT,
    FILE_NAME               VARCHAR NOT NULL,
    FILE_TYPE               VARCHAR NOT NULL,
    SOURCE_URL              VARCHAR NOT NULL,
    SOURCE_YEAR             NUMBER(4),
    SOURCE_MONTH            NUMBER(2),
    FILE_CHECKSUM           VARCHAR(64) NOT NULL,
    FILE_SIZE_BYTES         NUMBER,
    S3_BUCKET               VARCHAR NOT NULL,
    S3_KEY                  VARCHAR NOT NULL,
    PROCESSING_STATE        VARCHAR NOT NULL,
    PROCESSING_STARTED_AT   TIMESTAMP_TZ NOT NULL,
    PROCESSING_COMPLETED_AT TIMESTAMP_TZ,
    SOURCE_ROW_COUNT        NUMBER,
    ROWS_INSERTED           NUMBER,
    ROWS_UPDATED            NUMBER,
    ROWS_DELETED            NUMBER,
    ERROR_MESSAGE           VARCHAR,

    CONSTRAINT PK_LAND_REGISTRY_FILE_INGESTION_AUDIT
        PRIMARY KEY (FILE_INGESTION_ID),

    CONSTRAINT UQ_LAND_REGISTRY_FILE_CHECKSUM
        UNIQUE (FILE_TYPE, FILE_CHECKSUM),

    CONSTRAINT CK_LAND_REGISTRY_FILE_TYPE
        CHECK (FILE_TYPE IN ('ANNUAL', 'MONTHLY')),

    CONSTRAINT CK_LAND_REGISTRY_PROCESSING_STATE
        CHECK (PROCESSING_STATE IN ('STARTED', 'SUCCESS', 'FAILED'))
);