SELECT CURRENT_ACCOUNT();

SELECT *
FROM PROPERTY_ANALYTICS.RAW.STG_LAND_REGISTRY_PRICE_PAID
LIMIT 10;

DESCRIBE VIEW PROPERTY_ANALYTICS.RAW.STG_LAND_REGISTRY_PRICE_PAID;

DROP VIEW IF EXISTS PROPERTY_ANALYTICS.RAW.STG_LAND_REGISTRY_PRICE_PAID;


SELECT COUNT(*) FROM PROPERTY_ANALYTICS.MART.DIM_DATE;

SELECT COUNT(*) FROM PROPERTY_ANALYTICS.MART.DIM_PROPERTY;

SELECT COUNT(*) FROM PROPERTY_ANALYTICS.MART.FACT_PROPERTY_TRANSACTIONS;


SELECT COUNT(*) AS unmatched_properties
FROM PROPERTY_ANALYTICS.MART.FACT_PROPERTY_TRANSACTIONS
WHERE property_key IS NULL;


SELECT
    COUNT(*) AS unmatched_rows,
    COUNT_IF(t.postcode IS NULL) AS null_postcodes,
    COUNT_IF(t.paon IS NULL) AS null_paon,
    COUNT_IF(t.saon IS NULL) AS null_saon
FROM PROPERTY_ANALYTICS.INTERMEDIATE.INT_PROPERTY_TRANSACTIONS t
LEFT JOIN PROPERTY_ANALYTICS.MART.DIM_PROPERTY p
    ON t.postcode IS NOT DISTINCT FROM p.postcode
    AND t.paon IS NOT DISTINCT FROM p.paon
    AND t.saon IS NOT DISTINCT FROM p.saon
WHERE p.property_key IS NULL;

SELECT
    t.postcode,
    t.paon,
    t.saon,
    COUNT(*) AS transaction_count
FROM PROPERTY_ANALYTICS.INTERMEDIATE.INT_PROPERTY_TRANSACTIONS t
LEFT JOIN PROPERTY_ANALYTICS.MART.DIM_PROPERTY p
    ON t.postcode IS NOT DISTINCT FROM p.postcode
    AND t.paon IS NOT DISTINCT FROM p.paon
    AND t.saon IS NOT DISTINCT FROM p.saon
WHERE p.property_key IS NULL
GROUP BY
    t.postcode,
    t.paon,
    t.saon
ORDER BY transaction_count DESC
LIMIT 20;


SELECT
    transaction_id,
    COUNT(*) AS transaction_count
FROM PROPERTY_ANALYTICS.INTERMEDIATE.INT_PROPERTY_TRANSACTIONS
GROUP BY transaction_id
HAVING COUNT(*) > 1
ORDER BY transaction_count DESC
LIMIT 20;

SELECT
    transaction_id,
    COUNT(*) AS transaction_count,
    COUNT(DISTINCT price) AS distinct_prices,
    COUNT(DISTINCT date_of_transfer) AS distinct_dates,
    COUNT(DISTINCT postcode) AS distinct_postcodes
FROM PROPERTY_ANALYTICS.INTERMEDIATE.INT_PROPERTY_TRANSACTIONS
GROUP BY transaction_id
HAVING COUNT(*) > 1
ORDER BY transaction_count DESC
LIMIT 20;

SELECT COUNT(*) FROM PROPERTY_ANALYTICS.MART.DIM_DATE;
-- truncate table PROPERTY_ANALYTICS.MART.DIM_DATE;

SELECT COUNT(*) FROM PROPERTY_ANALYTICS.MART.DIM_PROPERTY;
-- truncate table PROPERTY_ANALYTICS.MART.DIM_PROPERTY;

SELECT COUNT(*) FROM PROPERTY_ANALYTICS.MART.FACT_PROPERTY_TRANSACTIONS;
-- truncate table PROPERTY_ANALYTICS.MART.FACT_PROPERTY_TRANSACTIONS;

SELECT *
FROM PROPERTY_ANALYTICS.MART.FACT_PROPERTY_TRANSACTIONS
LIMIT 10;

select * 
from PROPERTY_ANALYTICS.RAW.LAND_REGISTRY_PRICE_PAID
LIMIT 10;
-- truncate table PROPERTY_ANALYTICS.RAW.LAND_REGISTRY_PRICE_PAID;