
truncate table PROPERTY_ANALYTICS.MART.DIM_DATE;
truncate table PROPERTY_ANALYTICS.MART.DIM_PROPERTY;
truncate table PROPERTY_ANALYTICS.MART.FACT_PROPERTY_TRANSACTIONS;
truncate table PROPERTY_ANALYTICS.RAW.LAND_REGISTRY_PRICE_PAID; 